# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670
    hooks:
    -   id: mypy
# -   repo: local
#     hooks:
#     -   id: vue-cli-lint
#         name: vue cli lint
#         entry: npm
#         language: system
#         files: \.(ts|vue)$
#         args: [--prefix, './adre/server/frontend', run, lint, '--']
